format = """\
[LocalHost](green bold) \
$username\
$hostname\
$directory\
$git_branch\
$character\
"""

[username]
show_always = true
style_user = "bg:#000f22 fg:#88ffaa"
format = "[$user@]($style)"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "bg:#000f22 fg:white"
disabled = false

[directory]
style = "cyan bold"
truncation_length = 0
truncate_to_repo = false
format = "[\\[$path\\]]($style) "

[git_branch]
format = "- [$branch]($style) "

[character]
success_symbol = "[>](bold bg:#006090 fg:white)"
error_symbol = "[>](bold bg:#ef0000 fg:white)"
format = "\n$symbol "
